var ids = [];
var title = [];
var message = [];
var link = [];
var media_link = [];

var img_link;
var imgdata;

var hasImageLink;
var hasPushed;

var latestID;

//Reload the Function each 10s
$(function(){
  loadData()
  setInterval(loadData, 1000);
  pushEngine();
  setInterval(pushEngine, 5000);
});

//Return Default Notification Image
function getDefaultImage(notificationImage){
  return notificationImage;
}

function loadData(){

    //Your URL to the JSON File (Generated by the WordPress REST API PLUGIN )
    var url = "https://dominikwieners.de/wp-json/wp/v2/posts";
    $.getJSON( url, function(obj){

      for(i = 0; i < obj.length; i++){
        ids[i] = obj[Object.keys(obj)[i]].id;
        title[i] = obj[Object.keys(obj)[i]].title.rendered;
        message[i] = $(obj[Object.keys(obj)[i]].excerpt.rendered).text();
        link[i] = obj[Object.keys(obj)[i]].link;
        if(obj[Object.keys(obj)[0]].featured_media === 0){
          hasImageLink = false;
        }else{
          hasImageLink = true;
          media_link[i]= "https://dominikwieners.de/wp-json/wp/v2/media/"+ obj[Object.keys(obj)[i]].featured_media;
        }
      }

    });

    if(hasImageLink === true){
      $.getJSON( media_link[0], function(obj){

          img_link = obj.media_details.sizes.full.source_url;

          var xhr = new XMLHttpRequest();
          xhr.open("GET", img_link);
          xhr.responseType = "blob";
          xhr.onload = response;
          xhr.send();

          function response() {
           var urlCreator = window.URL || window.webkitURL;
           imgdata = urlCreator.createObjectURL(this.response);
         }

      });
    }else{
      //Default Notification Image
      imgdata = getDefaultImage("icon.png");
    }

}


function pushEngine(){

  chrome.notifications.onClicked.addListener(function(){
    if(hasPushed === true){
      window.open(link[0]);
      hasPushed = false;
    }
  });


  if(latestID === ids[0]){
    //no update
  }else if (latestID === undefined){

    //if no message was created before push a new message
    var firstRun ={
      type: "basic",
      title: title[0],
      message: message[0],
      iconUrl: imgdata
    }

    hasPushed = true;

    //create the chrome notification
    chrome.notifications.create(firstRun);

    latestID = ids[0];


  }else if(ids[0] !== latestID){

    var notify = {
      type: "basic",
      title: title[0],
      message: message[0],
      iconUrl: imgdata
    }

    hasPushed = true;

    //create the chrome notification
    chrome.notifications.create(notify);

    latestID = ids[0];

  }

}
